Tensors are a generalization of scalars, vectors, and matrices — they are the fundamental data structure in machine learning, especially in deep learning (e.g., TensorFlow, PyTorch).

In [15]:
import numpy as np

In [16]:
# 0 d tensor

a = np.array(4)

print(a)

print( 'dim : ' ,a.ndim)

4
dim :  0


In [17]:
# 1 d tensor
# vector

a = np.array([1,3,4])

print(a)

print( 'dim : ' ,a.ndim)

[1 3 4]
dim :  1


In [18]:
# 2 d tensor
# matrices

a = np.array([[1,3,4],[0,4,5]])

print(a)

print( 'dim : ' ,a.ndim)

print( 'shape :', a.shape)



[[1 3 4]
 [0 4 5]]
dim :  2
shape : (2, 3)


In [ ]:
# n d tensor

a = np.array([[[[1,3,4],[0,4,5]],[[1,3,4],[0,4,5]]]])

print(a)

print( 'dim : ' ,a.ndim)

print( 'rank :', a.ndim)

print( 'shape :', a.shape)

[[[[1 3 4]
   [0 4 5]]

  [[1 3 4]
   [0 4 5]]]]
dim :  4
rank : 4
shape : (1, 2, 2, 3)


| Tensor Type    | Rank | Example Shape       | Description                    |
| -------------- | ---- | ------------------- | ------------------------------ |
| **Scalar**     | 0    | `()`                | A single number (e.g., `5`)    |
| **Vector**     | 1    | `(n,)`              | A 1D array (e.g., `[1, 2, 3]`) |
| **Matrix**     | 2    | `(m, n)`            | A 2D array (e.g., table)       |
| **3D Tensor**  | 3    | `(m, n, p)`         | Stack of matrices              |
| **n-D Tensor** | n    | `(d1, d2, ..., dn)` | Any n-dimensional array        |


📌 Why Tensors Are Important in ML:

Input to neural networks is usually a tensor (e.g., images, text, audio).

Model weights and activations are stored as tensors.

Tensor operations are highly optimized on GPUs.

🧠 Examples in Practice:

A grayscale image = 2D tensor (height × width)

A color image = 3D tensor (height × width × channels)

A batch of images = 4D tensor (batch × height × width × channels)